name: Compilar Multiplataforma
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencias Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libx11-dev libxkbcommon-dev libfontconfig1-dev libasound2-dev libsqlite3-dev
      - name: Configurar y Compilar
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name: Subir Artefactos
        uses: actions/upload-artifact@v4
        with:
          name: EasyPresenter-${{ runner.os }}
          path: |
            build/Release/*.exe
            build/*.deb
